## Get list of databases
library(readxl)
list <- read_excel("./database list.xlsx")
names <- names(list)

## Generate one Rmd file per database
for (i in 1:length(list$Database)) {

    ## Get lines
    ## Column 1 has Acronym/Short name to be used as rmd file name
    ## Column 2 has the Database name to be used as the main title
    ## Columns 3-next to last have the description fields
    ## Last column has the date of last update (for internal use)
    lines <- c("\\mainmatter",
               "",
               "<!-- Generated by generateRmd.R; do not edit by hand  -->",
               "", 
               paste0("# ", as.character(list[i,2])), "")
    for (j in 3:(ncol(list)-1)){
        lines <- c(lines, 
                   paste0("## ", names[j]), 
                   as.character(list[i, j]),
                   "")
    } 
    
    ## Open connection to file
    rmdFileConn <- file(paste0(
        formatC(i, width=3, format="d", flag="0"),
        "-",
        tolower(list$Acronym[i]), 
        ".Rmd"))

    ## Write lines to file
    writeLines(lines, rmdFileConn)

    ## Close connection
    close(rmdFileConn)
    
}

